#This file stores configuration options for Iris, such as the currently active shaderpack
#Fri Mar 27 23:54:27 CET 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=32
shaderPack=
