#This file stores configuration options for Iris, such as the currently active shaderpack
#Tue Apr 07 17:38:55 CEST 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=8
shaderPack=
